version: "3.9"

services:
  gmweb:
    image: ghcr.io/githubphadnis/golfmeadows_web:latest
    container_name: gmweb
    restart: unless-stopped
    ports:
      - "4273:4273"
    environment:
      - SOCIETY_NAME=${SOCIETY_NAME}
      - GOOGLE_DRIVE_API_KEY=${GOOGLE_DRIVE_API_KEY}
      - GOOGLE_DRIVE_HERO_FOLDER_ID=${GOOGLE_DRIVE_HERO_FOLDER_ID}
      - GOOGLE_DRIVE_DOCS_FOLDER_ID=${GOOGLE_DRIVE_DOCS_FOLDER_ID}
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - SUPER_ADMIN_EMAIL=${SUPER_ADMIN_EMAIL}
      - PORT=4273
    volumes:
      - /home/prakalp/docker/gmweb/data/db:/app/data/db
      - /home/prakalp/docker/gmweb/data/content:/app/data/uploads
